---
name: permissions-web
bundle_prefix:
  - ycappuccino.storage
  - ycappuccino.endpoints_storage
  - ycappuccino.endpoints_service
  - ycappuccino.http_server
  - ycappuccino.permissions
  - ycappuccino.remote.dispatch
  - ycappuccino.remote.capabilities
  - webhost
  - ycappuccino.hosts
layers:
  ycappuccino_storage_memory:
    active: true
components:
  JwtAuthentication:
    key: demo-secret-key-not-for-production-use
  PasswordLogin:
    key: demo-secret-key-not-for-production-use
  FrontendShell:
    key: demo-secret-key-not-for-production-use
config:
  http_server:
    active: true
    port: 8180
    ip: localhost
  shell:
    console: false
